#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { listGuideMarkdownFiles } from './guide-docs';

const OUTPUT_PATH = path.join(process.cwd(), 'src/features/guides/generated-docs.ts');

function toImportName(fileName: string, index: number): string {
  const stem = fileName.replace(/\.md$/, '');
  const candidate = stem
    .replace(/[^A-Za-z0-9]+(.)/g, (_, char: string) => char.toUpperCase())
    .replace(/^[^A-Za-z_]+/, '')
    .replace(/[^A-Za-z0-9_]/g, '');
  return `${candidate || 'guide'}Md${index + 1}`;
}

export function generateGuideRegistrySource(files = listGuideMarkdownFiles()): string {
  const imports = files
    .map((fileName, index) => {
      const importName = toImportName(fileName, index);
      return `import ${importName} from '../../../docs/${fileName}?raw';`;
    })
    .join('\n');

  const entries = files
    .map((fileName, index) => {
      const importName = toImportName(fileName, index);
      return `  '${fileName}': ${importName},`;
    })
    .join('\n');

  return `// This file is generated by scripts/generate-guide-registry.ts.
// Edit docs/*.md, then run npm run guides:generate.

${imports}

export const DOCS_MARKDOWN: Record<string, string> = {
${entries}
};
`;
}

export function writeGuideRegistry(): void {
  const source = generateGuideRegistrySource();
  fs.writeFileSync(OUTPUT_PATH, source);
  console.log(`Generated ${path.relative(process.cwd(), OUTPUT_PATH)}`);
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  writeGuideRegistry();
}
